### ISSUE TITLE
Unresolved compilation problem: VTHeaderForest#getRoots() must override superclass method

### ISSUE THREAD

**Issue by tfmorris** [usc-isi-i2/szeke#1]
When attempting to import a CSV file, I got a large number of errors of the following form logged:

ERROR [qtp1743021837-24 - /RequestController](CSVFileImport.java:157) - More da
ta elements detected in the row than number of headers!

follow by the stack trace below.  The browser remains stuck with the "Please wait" spinner showing and never returns.

2012-08-30 19:04:54.634:WARN:oejs.ServletHandler:Error for /RequestController
java.lang.Error: Unresolved compilation problem: |?The method getRoots() of type
 VTHeaderForest must override a superclass method|
        at edu.isi.karma.view.tableheadings.VTHeaderForest.getRoots(VTHeaderFore
st.java:38)
        at edu.isi.karma.rep.hierarchicalheadings.HHTree.constructHHTree(HHTree.
java:43)
        at edu.isi.karma.controller.update.WorksheetHierarchicalHeadersUpdate.ge
nerateJson(WorksheetHierarchicalHeadersUpdate.java:66)
        at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateCo
ntainer.java:74)
        at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateCo
ntainer.java:90)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.ja
va:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:558
)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:488)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:520)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:972)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
417)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:192)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:906)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:117)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(Cont
extHandlerCollection.java:250)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerColl
ection.java:149)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:110)
        at org.eclipse.jetty.server.Server.handle(Server.java:346)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.
java:442)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpCo
nnection.java:941)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)

```
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnecti
```

on.java:52)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEn
dPoint.java:586)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEnd
Point.java:44)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:598)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:533)
        at java.lang.Thread.run(Thread.java:722)

**Comment by tfmorris** [comment]
This problem was apparently introduced by m2e when the project was imported into Eclipse.  Apparently it has Java 1.5 as the default execution environment, so it overrode the previous setting in the .classpath file.

Since the project requires Java 1.6 or later, it's probably worth specifying that explicitly in the pom by adding this to the build plugins sections:

```
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
    </plugin>
```

**Comment by shubhamg** [comment]
I will add this code snippet in the pom.xml in the next version. Thanks!
